---
title: "Hierarchical clusting of tumor samples using the vst expression data of top 100 most variable microRNAs with the tool the Consensus Cluster Plus"
author: "Jieqiong Dai"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
      html_document:
        code_folding: hide
        toc: true
        toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Reads in miRNA reads count data
```{r,message=FALSE,warning=FALSE}
library(DESeq2)
mi <- read.csv("phase1234_miRNA_reads_count_ready.csv",header=T,row.names=1)
```

# Read in sample table
```{r,message=FALSE,warning=FALSE}
sample <- read.csv("miRNA_sample_table.csv",header=T,row.names=1)
```

# Match reads count and sample tables
```{r,message=FALSE,warning=FALSE,results='hide'}
sample <- sample[order(rownames(sample)),]
mi <- mi[,colnames(mi) %in% rownames(sample)]
mi <- mi[,order(colnames(mi))]
nrow(mi)
ncol(mi)
colnames(mi) == rownames(sample)
```

# Get get vst data for all samples
```{r,message=FALSE,warning=FALSE}
dds <- DESeqDataSetFromMatrix(countData = mi,colData = sample,design = ~ Phase + Sex + probality + FinalDriverPathway.10Jan2020)
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
dds <- DESeq(dds,minReplicatesForReplace=Inf)
vst <- vst(dds,blind = F,nsub = 300)
write.csv(assay(vst),"miRNA_vst.csv")
```

# Take tumor samples only
```{r,message=FALSE,warning=FALSE}
sample_tu <- subset(sample, Specimen.Type.ID=="Primary Tumor")
vst_tu <- vst[,colnames(vst)%in%rownames(sample_tu)]
vst_tu <- vst_tu[,order(colnames(vst_tu))]
vst_tu
vst_tu_data <- assay(vst_tu)
```

# Get top 100 most variable miRNAs
```{r,message=FALSE,warning=FALSE}
TopVarGenes <- head(order(rowVars(vst_tu_data),decreasing=TRUE),100)
top_vst <- vst_tu_data[TopVarGenes, ]
write.csv(rownames(top_vst),"top100_most_variable_miRNAs_inTumortotalRNA.csv")
```

# Hierarchical clusting with the tool the Consensus Cluster Plus
```{r,message=FALSE,warning=FALSE}
library(ConsensusClusterPlus)
results2 <- ConsensusClusterPlus(top_vst,maxK=10,reps=100,pItem=0.9,pFeature=1,clusterAlg="hc",distance="pearson",plot="png",title="top100_most_variable_miRNAs_tumor_sample_clustering_CCP")
write.csv(results2[[2]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k2.csv")
write.csv(results2[[3]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k3.csv")
write.csv(results2[[4]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k4.csv")
write.csv(results2[[5]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k5.csv")
write.csv(results2[[6]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k6.csv")
write.csv(results2[[7]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k7.csv")
write.csv(results2[[8]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k8.csv")
write.csv(results2[[9]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k9.csv")
write.csv(results2[[10]]$consensusClass,"miRNA_tumor_clust_CCP_top100mostvariable_k10.csv")
```
